### ISSUE TITLE
help with installation 

### ISSUE THREAD

**Issue by savi317** [fosterlab/PrInCE#1]
Hello, I have been trying to install PrInCE but have been experiencing several issues. First, the Stacey et al. (2017) manuscript says PrInCE is a standalone program but it appears that R version >=3.6.0 is required? I also do not see an icon to access the program. 

Second, upon install of R 3.6.0, and attempting to also install PrInCE I get the error that “installation of package ‘ncdf4’ had non-zero exit status.” This error seems to be somewhat common, and some google searching provided the recommendation of installing package ‘netcdf’ as a solution; however, when attempting to install package ‘netcdf’ I get the error that this package is not available for R version 3.6.0. Are there any tips/tricks/advice that you could pass along that may help with the installation of your program? Many thanks in advance.

**Comment by GregStacey** [comment]
The "standalone" mentioned in Stacey et al. (2017) is the Matlab standalone (https://github.com/fosterlab/PrInCE-Matlab).

I'll check the netcdf error.

**Comment by savi317** [comment]
Thanks for your response, although this is misleading as it is mentioned in Stacey et al. (2017) “PrInCE is available as a standalone program for Windows or Mac OSX, as well as a Matlab package. **Matlab is not required to run standalone versions of PrInCE** but it was selected initially due to superior curve fitting tools compared to other environments.”

**Comment by GregStacey** [comment]
Matlab's not required, either for this R version or the Matlab-compiled standalone. The Matlab standalone was compiled from Matlab code but doesn't require Matlab to run. There are detailed instructions on how to do that at https://github.com/fosterlab/PrInCE-Matlab (look for "Mac and PC users can run PrInCE without owning Matlab").

**Comment by savi317** [comment]
excellent, thank you for your help.
