### ISSUE TITLE
MS method

### ISSUE THREAD

**Issue by zmb19** [fosterlab/PrInCE#2]
Hello :)

I was wondering if it mattered whether the protein quantitations were obtained using SILAC or if a label-free data set could be used.
If so, which output from maxQuant would be used as the dataset?

Thanks so much for the package!

**Comment by skinnider** [comment]
I don’t think that we have actually used PrInCE on a non-SILAC dataset so far, but there is no reason label-free shouldn’t work (aside from slightly lower quantitation accuracy) and in fact I’m hoping to try this myself in the near future. 

As far as which label-free quantitation algorithm will produce the best results, I’m not aware of any empirical studies that have directly assessed protein correlation profiling but in the context of proteomics more generally, [this paper](https://www.ncbi.nlm.nih.gov/pubmed/28217993) seems to suggest MaxLFQ would be a good option.

Mike

**Comment by GregStacey** [comment]
Just to add - dataset 3 in the PrInCE paper is raw intensity values, i.e. not SILAC ratios (https://bmcbioinformatics.biomedcentral.com/track/pdf/10.1186/s12859-017-1865-8, D3). That was analyzed by PrInCE just fine.

In principal the type of protein quantification is not important (although some quantification methods will be less noisy/biased than others). As far as PrInCE is concerned, any data type that can be expressed in the form (protein amount) vs (fraction) should work, as long as co-varying protein amount is evidence of interaction.
